### ISSUE TITLE
Error in building fhem-docker image

### ISSUE THREAD

**Issue by 57k** [fhem/fhem-docker#12]
hello everybody,

maybe someone is experiencing the same issue while building the container image. 

Step 59/68 : COPY src/fhem/trunk/fhem/ /fhem/
ERROR: Service 'fhem' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder657142930/src/fhem/trunk/fhem: no such file or directory

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

$ docker version
Client:
Version: 18.09.0
API version: 1.39
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:49:01 2018
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.0
API version: 1.39 (minimum version 1.12)
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:16:44 2018
OS/Arch: linux/amd64
Experimental: false

If this trunk folder is related to the SVN repository of FHEM - is there any chance to include this into the Dockerfile?

Just to mention - I don't want to use the pre-build docker image

Thanks / Cheers, Jens

**Comment by jpawlowski** [comment]
Checkout of the FHEM sources is not done via Docker, it is handled outside as part of the Travis CI build environment setup. If you want to replicate that, you need to take care of it yourself.
