### ISSUE TITLE
Empty new lines written to docker log file

### ISSUE THREAD

**Issue by passibe15** [fhem/fhem-docker#128]
**Describe the bug**
Docker logs get flooded with empty new lines, i.e. the file gets appended even though there is nothing new in the FHEM log file.
If the container is recreated the docker logs are deleted, otherwise they grow quite large (under `/var/lib/docker/containers/<id>/<id>-json.log`).

**To Reproduce**
Run `sudo docker logs <name of container> -f` and watch.

**Expected behavior**
No adding of blank new lines if there is nothing new in the FHEM log file.

**Desktop (please complete the following information):**
 - OS: Debian bookworm
 - Docker version: 24.0.6 (compose version 2.21.0)
 - Image version: 3.2.3-bullseye

**Additional context**
I investigated the issue and it seems like there is a problem in [entry.sh](https://github.com/fhem/fhem-docker/blob/dev/src/entry.sh) where on line 459 `printf '%s\n' "${logArray[@]}"` is executed, even though `$logArray` is empty.

I fixed it by moving the contents of line 459 into the else-branch on line 464, i.e. PrintNewLines looks like this now:
```
function PrintNewLines {
  LOGFILENAME=$( date +"${LOGFILE}" )
  if [ -s "${LOGFILENAME}" ]; then
    mapfile -t logArray < <(tail -n "+$((${OLDLINES} + 1))" "${LOGFILENAME}" )
    [ -n "$1" ] && printf '%s\n' "${logArray[@]}" | grep -q -e "$1" && FOUND=true || FOUND=false
    if [ ${#logArray[@]} -eq 0 ]; then
      MAXLINES=$( wc -l < "${LOGFILENAME}" )
  	  [ ${OLDLINES} -gt ${MAXLINES} ] && OLDLINES=-1  # logfile rotation
    else
      printf '%s\n' "${logArray[@]}" # moved to here
      OLDLINES=$((${OLDLINES} + ${#logArray[@]} ))
    fi
  fi
}
```

While this does seem to fix the bug, I haven't tested it yet with log rotation and don't know if there are other implications from moving the printf statement …

**Comment by sidey79** [comment]
I saw this bug before, but not in this Image version.

Also i am currently not able to reproduce this

**Comment by passibe15** [comment]
Okay, interesting.
I just tested it with a fresh service, i.e. docker-compose.yml:
```
version: "3.3"
services:
  fhemtest:
    image: ghcr.io/fhem/fhem-docker:3-bullseye
    container_name: fhemtest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
```
and can confirm that the bug (still) exists with running ```sudo docker logs ha_fhemtest -f```.

**Comment by sidey79** [comment]
Can you check that you are really running container version 3.2.3?

Can you run a inspect, on the started container like this:
`docker inspect <containerID>| grep version`

**Comment by passibe15** [comment]
Yes, I am running 3.2.3:
```
                "com.docker.compose.version": "2.21.0",
                "org.fhem.version": "",
                "org.opencontainers.image.version": "3.2.3-bullseye"
```
Even if I pin the version in the docker-compose.yml to `ghcr.io/fhem/fhem-docker:3.2.3-bullseye` it's the same. I also just tested it on another system with the compose-file posted above (also Debian bullseye) and the bug is still present.

Just from a logical point of view:
There is no check in place whether `$logArray` is actually populated. So `printf '%s\n' "${logArray[@]}"` is executed every time `PrintNewLines` runs, independent of what `$logArray` contains (or doesn't contain). There is simply nothing there preventing it from printing `\n` every time it runs.

On another note: My "fix" from above, moving `printf …` into the else-branch works flawlessly, even after two nightly logrotates now.

**Comment by sidey79** [comment]
I see a similar problem only with one single newline.
For this i have already prepared a fix in the bookworm branch

**Comment by passibe15** [comment]
What do you mean with "only with one single newline"? Are you now able to recreate the issue or not?

And sorry to bring this up again, but: What check is in place so that `printf` is executed only if there is something in `$logArray` to be printed?

**Comment by sidey79** [comment]
> What do you mean with "only with one single newline"? Are you now able to recreate the issue or not?

I can't reproduce the error, with `sudo docker logs <name of container> -f`
Bit in the logfile sometimes newlines are added
`{"log":"\n","stream":"stdout","time":"2023-09-12T15:06:34.882448783Z"} `


> And sorry to bring this up again, but: What check is in place so that `printf` is executed only if there is something in `$logArray` to be printed?

Currently, none is implemented, i'll fix this
