### ISSUE TITLE
Rewrite of entry.sh / question on contributing

### ISSUE THREAD

**Issue by HaraldR42** [fhem/fhem-docker#138]
Dear maintainers,

I did a fairly massive rewrite of the entry.sh script. It mainly addresses:

- In the past there were a number of regressions in sending the log to the console.
  With my new version, sending the log to the console is done by a background process heavily using "tail",
  but also taking care of line-buffering, changed log file etc.
  And performance wise it uses much less calls to the various unix tools, as it doesn't poll any more.
- Checking for process startup and process termination is more robust.
- General rewrite, making the script more modular and robust.

So my question is: Should I make a pull request on the original entry.sh, resulting in a massive (and mostly useless diff),
or should I request pulling a new file?

Thx in advance
Harald

**Comment by sidey79** [comment]
You can open a PR. May i then start multiple discussions for a better understanding.

**Comment by sidey79** [comment]
Your updated script will be included in version 4 of the image

**Comment by HaraldR42** [comment]
Hi @sidey79 ,
Thanks a lot for your additional contributions, and thanks for merging!
Cheers,
Harald
