### ISSUE TITLE
Update nodejsVersion to >18.x or higher for support of npm >10.x 

### ISSUE THREAD

**Issue by forestvogo** [fhem/fhem-docker#143]
Using the latest provided version of dockerized FHEM there are issues updating npm inside of docker to 10.x. The requirements therefore are requesting nodejsVersion >18.x instead of the provided version 16.20.2.

What else is needed from my side?

Thanks in advance and best regards
Volker

**Comment by sidey79** [comment]
What ist the usecase of running npm packages inside of FHEM container instead of using a seperate container?

**Comment by forestvogo** [comment]
Hi @sidey79 ,

nothing from my side. It is only annoying to see the FHEM system showing a red icon for not being up-to-date. 

Therefore I was trying to find a solution by getting the latest versions into the system. 

Cheers Volker

**Comment by sidey79** [comment]
The solution i recommend is using the minimal Image :

ghcr.io/fhem/fhem-minimal-docker:3.3.1-buster

There ist no nodejs installed, so no warning.

**Comment by forestvogo** [comment]
@sidey79 will give it a try. Buster?  Quite old bookworm is already out. Any chance on this?

thx and cheers 
Volker

**Comment by sidey79** [comment]
Bullseye ist also available, but bookworm isn't finished today:

docker pull ghcr.io/fhem/fhem-minimal-docker:3.3.1-bullseye

Those images are updated at regular base.

**Comment by git-developer** [comment]
The latest bullseye image `ghcr.io/fhem/fhem-docker:dev-bullseye` contains nodejs 18, so this issue may probably be closed.

**Comment by forestvogo** [comment]
Hi @git-developer , just confirmed by updating my system. Thx a lot for your efforts. Will mark this as resolved.
