### ISSUE TITLE
Reduce size of v4 minimal image

### ISSUE THREAD

**Issue by git-developer** [fhem/fhem-docker#197]
_(Migrated from [#115](https://github.com/fhem/fhem-docker/issues/115#issuecomment-2046608805))_

This is a request to reduce the size of the v4 minimal image.

The minimal image has grown significantly between v3 and v4:
```
$ docker images | grep fhem
ghcr.io/fhem/fhem-minimal-docker   3.3.1-bullseye                       c9b1f0c873e7   4 months ago    635MB
ghcr.io/fhem/fhem-minimal-docker   dev-bullseye                         cf28244b08a3   12 hours ago    905MB
```

Maybe a switch to the slim base image helps (not verified).
```
$ docker image ls | grep perl
perl                 5.36.3-slim-bullseye   52a305760451   3 weeks ago     132MB
perl                 5.36.3-bullseye        61325f916a7e   3 weeks ago     692MB
```

**Comment by sidey79** [comment]
Maybe this ist possible, during Installation of CPAN modules they need some build tools.

We can try to copy all cpan modules later to a slim based image layer. But first goal ist to get rid of some build bugs.

**Comment by git-developer** [comment]
```
$ docker image ls | grep fhem
ghcr.io/fhem/fhem-minimal-docker   dev-bullseye                         e9e2497c9e17   7 hours ago      531MB
ghcr.io/fhem/fhem-minimal-docker   3.3.1-bullseye                       c9b1f0c873e7   5 months ago     635MB
```

Thanks a lot!
