### ISSUE TITLE
Device::SerialPort is missing in v4 arm images

### ISSUE THREAD

**Issue by git-developer** [fhem/fhem-docker#198]
_(Migrated from [#115](https://github.com/fhem/fhem-docker/issues/115#issuecomment-2046608805))_

The v4 `arm/v7` image does not contain the `Device::SerialPort` module which is required for many USB devices:

```
$ docker run --rm -ti --entrypoint /bin/sh ghcr.io/fhem/fhem-minimal-docker:3.3.1-bullseye -c "perl -e 'use Device::SerialPort'"

$ docker run --rm -ti --entrypoint /bin/sh ghcr.io/fhem/fhem-minimal-docker:dev-bullseye -c "perl -e 'use Device::SerialPort'"
Can't locate Device/SerialPort.pm in @INC (you may need to install the Device::SerialPort module) (@INC contains: /usr/local/lib/perl5/site_perl/5.36.3/arm-linux-gnueabihf-64int /usr/local/lib/perl5/site_perl/5.36.3 /usr/local/lib/perl5/vendor_perl/5.36.3/arm-linux-gnueabihf-64int /usr/local/lib/perl5/vendor_perl/5.36.3 /usr/local/lib/perl5/5.36.3/arm-linux-gnueabihf-64int /usr/local/lib/perl5/5.36.3) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

The `arm64` build is [probably](https://github.com/fhem/fhem-docker/actions/runs/8676079068) affected, too.

Related PR: https://github.com/fhem/fhem-docker/pull/196

**Comment by sidey79** [comment]
@git-developer  @

The currently build image 
`ghcr.io/fhem/fhem-minimal-docker:dev-bullseye@sha256:f94fdbf985a5d7bd4e0d15d624d90771ba554af885f366df43987b8eb0bee5b7
`
Has Device::SerialPort 

Name | Version
-- | --
Algorithm::DecisionTree | 3.430
Algorithm::Diff | 1.201
Alien::Build | 2.800
Alien::Build::Plugin::Download::GitLab | 0.010
Alien::Libxml2 | 0.190
Alien::Sodium | 2.000
App::cpanminus | 1.704700
Archive::Zip | 1.680
Array::RefElem | 1.000
Authen::OATH | 2.000001
Authen::SASL | 2.170000
B::Hooks::EndOfScope | 0.280
B::Hooks::OP::Check | 0.220
bareword::filehandles | 0.007
Bit::Vector | 7.400
Cache::Cache | 1.080
Call::Context | 0.030
Canary::Stability | 2013.000
Capture::Tiny | 0.480
Carp::Assert | 0.220
Carp::Clan | 6.080
CGI | 4.640
CGI::Session | 4.480
CHI | 0.610
CHI::Driver::Redis | 0.100
Class::Accessor | 0.510
Class::Data::Inheritable | 0.090
Class::Inspector | 1.360
Class::Load | 0.250
Class::Loader | 2.030
Class::Method::Modifiers | 2.150
Class::Singleton | 1.600
Clone | 0.460
common::sense | 3.750
Convert::Base32 | 0.060
Cosmoloj::UnitSimple | ?
CPAN::Meta::Requirements | 2.143
Cpanel::JSON::XS | 4.370
Crypt::Argon2 | 0.022
Crypt::CBC | 3.040
Crypt::ECB | 2.230
Crypt::MySQL | 0.040
Crypt::OpenSSL::AES | 0.190
Crypt::OpenSSL::Guess | 0.150
Crypt::PBKDF2 | 0.161520
Crypt::Random | 1.540
Crypt::RC4 | 2.020
Crypt::Rijndael | 1.160
Crypt::Rijndael_PP | 0.050
Crypt::URandom | 0.400
CryptX | 0.080
Data::Dump | 1.250
Data::OptList | 0.114
Data::Perl | 0.002011
Data::UUID | 1.227
Date::Parse | 2.330
DateTime | 1.650
DateTime::Event::Sunrise | 0.050600
DateTime::Format::Strptime | 1.790
DateTime::Locale | 1.410
DateTime::Set | 0.390000
DateTime::TimeZone | 2.620
DBD::MariaDB | 1.230
DBD::mysql | 4.051
DBD::Pg | 3.018000
DBD::SQLite | 1.740
DBI | 1.643
Devel::CheckLib | 1.160
Devel::Size | 0.830
Devel::Size::Report | 0.130
Devel::StackTrace | 2.050
Device::SerialPort | 1.040
Device::SMBus | 1.150
Digest::CMAC | 0.040
Digest::CRC | 0.240
Digest::HMAC | 1.040
Digest::JHash | 0.100
Digest::Perl::MD5 | 1.900
Digest::SHA1 | 2.130
Digest::SHA3 | 1.050
Dist::CheckConflicts | 0.110
Email::Date::Format | 1.008
Encode::Detect | 1.010
Encode::Locale | 1.050
Error | 0.170290
Eval::Closure | 0.140
Exception::Class | 1.450
Exporter::Tiny | 1.006002
ExtUtils::Config | 0.008
ExtUtils::Depends | 0.800100
ExtUtils::Helpers | 0.026
ExtUtils::InstallPaths | 0.012
ExtUtils::MakeMaker::CPANfile | 0.090
ExtUtils::PkgConfig | 1.160
FFI::CheckLib | 0.310
FFI::Platypus | 2.080
FigAnim | 0.100
File::chdir | 0.101100
File::Copy::Recursive | 0.450
File::HomeDir | 1.006
File::Listing | 6.160
File::Path::Expand | 1.020
File::ShareDir | 1.118
File::ShareDir::Install | 0.140
File::Slurp | 9999.320
File::Which | 1.270
Finance::Quote | 1.590
Geo::IP::PurePerl | 1.260
GnuPG::Interface | 1.040
Hash::MoreUtils | 0.060
HTML-TableExtract | ?
HTML::Parser | 3.820
HTML::Selector::XPath | 0.280
HTML::Tagset | 3.240
HTML::TokeParser::Simple | 3.160
HTML::Tree | 5.070
HTML::TreeBuilder::XPath | 0.140
HTTP::CookieJar | 0.014
HTTP::Cookies | 6.110
HTTP::Daemon | 6.160
HTTP::Date | 6.060
HTTP::Message | 6.450
HTTP::Negotiate | 6.010
Image::ExifTool | 12.760
Image::Info | 1.440
Image::LibRSVG | 0.070
Image::Size | 3.300
indirect | 0.390
Inline | 0.860
Inline::C | 0.820
IO::Framed | 0.160
IO::HTML | 1.004
IO::Interface | 1.090
IO::SessionData | 1.030
IO::SigGuard | 0.150
IO::Socket::Multicast | 1.120
IO::Socket::SSL | 2.085
IO::Socket::Timeout | 0.320
IO::String | 1.080
IO::Stringy | 2.113
JSON | 4.100
JSON::Any | 1.400
JSON::MaybeXS | 1.004005
JSON::XS | 4.030
libxml-perl | ?
Linux::Inotify2 | 2.300
Linux::Input | 1.030
Lirc::Client | 2.020
List::MoreUtils | 0.430
List::MoreUtils::XS | 0.430
Log::Any | 1.717
LWP | 6.770
LWP::MediaTypes | 6.040
LWP::Online | 1.080
LWP::Protocol::https | 6.140
Mail::GnuPG | 0.230
Mail::IMAPClient | 3.430
MailTools | 2.210
Math::ConvexHull | 1.040
Math::Expression::Evaluator | 0.003002
Math::Pari | 2.030523
Math::Polygon | 1.100
Math::Random | 0.720
MIME::Base64::URLSafe | 0.010
MIME::Lite | 3.033
MIME::Tools | 5.514
MIME::Types | 2.260
Module::Build | 0.423400
Module::Build::Tiny | 0.047
Module::CPANfile | 1.100400
Module::Find | 0.160
Module::Implementation | 0.090
Module::Pluggable | 5.200
Module::Runtime | 0.016
Mojolicious | 9.360
Moo | 2.005005
MooX::HandlesVia | 0.001009
MooX::late | 0.100
MooX::Types::MooseLike | 0.290
MooX::Types::MooseLike::Numeric | 1.030
Mozilla::CA | 20231213.000
MRO::Compat | 0.150
multidimensional | 0.014
namespace::autoclean | 0.290
namespace::clean | 0.270
Net::Address::IP::Local | 0.001002
Net::Bonjour | 0.960
Net::DNS | 1.440
Net::FTPSSL | 0.420
Net::HTTP | 6.230
Net::Jabber | 2.000
Net::MQTT | ?
Net::OAuth | 0.280
Net::OpenSSH | 0.840
Net::SIP | 0.836
Net::SMTP::SSL | 1.040
Net::SNMP | 6.000001
Net::SSLeay | 1.940
Net::Telnet | 3.050
Net::UPnP | 1.004006
Net::XMPP | 1.050
Nmap::Parser | 1.370
OLE::Storage_Lite | 0.220
Package::Stash | 0.400
Package::Stash::XS | 0.300
Params::Util | 1.102
Params::Validate | 1.310
Params::ValidationCompiler | 0.310
Parse::Distname | 0.050
Parse::RecDescent | 1.967015
Path::Tiny | 0.144
Pegex | 0.750
Perl | 5.036003
Perl::PrereqScanner::NotQuiteLite | 0.991700
PerlIO::via::Timeout | 0.320
Promise::ES6 | 0.280
Protocol::DBus | 0.220
Readonly | 2.050
Redis | 2.000
Ref::Util | 0.204
Ref::Util::XS | 0.117
Regexp::Trie | 0.020
RiveScript | 2.000004
Role::Hooks | 0.008
Role::Tiny | 2.002004
RPC::XML | 1.610
Set::Infinite | 0.650
SOAP::Lite | 1.270
Sodium::FFI | 0.009
Sort::Versions | 1.620
Specio | 0.480
Spiffy | 0.460
Spreadsheet::ParseExcel | 0.660
Spreadsheet::XLSX | 0.180
Statistics::ChiSquare | 1.000000
strictures | 2.000006
String::RewritePrefix | 0.009
String::Util | 1.340
Sub::Exporter | 0.991
Sub::Exporter::Progressive | 0.001013
Sub::HandlesVia | 0.050000
Sub::Identify | 0.140
Sub::Install | 0.929
Sub::Override | 0.100
Sub::Quote | 2.006008
Sub::Uplevel | 0.280000
Switch | 2.170
Sys::Mmap | 0.200
Task::Weaken | 1.060
Test::Base | 0.890
Test::Class | 0.520
Test::Deep | 1.204
Test::Deep::UnorderedPairs | 0.006
Test::Differences | 0.710
Test::Exception | 0.430
Test::Fatal | 0.017
Test::JSON | 0.110
Test::Mock::Redis | 0.220
Test::Pod | 1.520
Test::Requires | 0.110
Test::SharedFork | 0.350
Test::TCP | 2.220
Test::Warn | 0.370
Text::Diff | 1.450
Text::Iconv | 1.700
Text::Template | 1.610
Text::Unaccent | 1.080
Time::Duration | 1.210
Time::Duration::Parse | 0.160
Try::Tiny | 0.310
Type::Tiny | 2.004000
Types::Serialiser | 1.010
UNIVERSAL::require | 0.190
URI | 5.280
Variable::Magic | 0.640
Web::Scraper | 0.380
WWW::Jawbone::Up | 1.032004
WWW::RobotRules | 6.020
X::Tiny | 0.220
XML::DOM | 1.460
XML::LibXML | 2.021000
XML::NamespaceSupport | 1.120
XML::Parser | 2.470
XML::Parser::Lite | 0.722
XML::RegExp | 0.040
XML::SAX | 1.020
XML::SAX::Base | 1.090
XML::SAX::Expat | 0.510
XML::Simple | 2.250
XML::Stream | 1.240
XML::Twig | 3.520
XML::XPath | 1.480
XML::XPathEngine | 0.140
XML::XSLT | 0.480
XString | 0.005
XXX | 0.380
YAML | 1.310
YAML::PP | 0.038000
YAML::Tiny | 1.740


It would be nice, to have this output for every build run somewhere like a build result

**Comment by git-developer** [comment]
I can confirm that both latest dev images (minmal and extended) contain `Device::SerialPort` now. Thanks!

> It would be nice, to have this output for every build run somewhere like a build result

That should be possible as build artifact (in analogy to the [cpanfiles](https://github.com/fhem/fhem-docker/actions/runs/8676705370)). It could also be added to the release package, although I'm not sure if this would be of use for someone.

To avoid such issues in future, a test could be helpful that checks if the expected modules are available.

**Comment by sidey79** [comment]
For AMD64 Image a test is executed, but most developers do not care for a basic module test.

Running the ARM Images isn't easy because there ist no runtime environment provided by GitHub.

Doing a grep for failing installs would be possible.

Can we close this issue?

**Comment by git-developer** [comment]
Of course, this issue has been resolved. Thanks!
