### ISSUE TITLE
ERROR: Service 'habridge' failed to build

### ISSUE THREAD

**Issue by guitar9** [fhem/fhem-docker#20]
I am using raspberry PI and i get this error when I want enter docker-compose up.
I followed  the steps in the youtube video.

this is the output:

```
Building habridge
Step 1/7 : FROM java:8-jdk
 ---> d23bdf5b1b1b
Step 2/7 : MAINTAINER Matthias Kleine <info@haus-automatisierung.com>
 ---> Using cache
 ---> 0d7b74e373c4
Step 3/7 : ENV BRIDGE_VERSION 5.2.1
 ---> Using cache
 ---> ededec52eb44
Step 4/7 : RUN mkdir -p /opt/habridge && wget https://github.com/bwssytems/ha-bridge/releases/download/v${BRIDGE_VERSION}/ha-bridge-${BRIDGE_VERSION}.jar -O /opt/habridge/ha-bridge-${BRIDGE_VERSION}.jar
 ---> Running in a48683746bf2
standard_init_linux.go:207: exec user process caused "exec format error"
ERROR: Service 'habridge' failed to build: The command '/bin/sh -c mkdir -p /opt/habridge && wget https://github.com/bwssytems/ha-bridge/releases/download/v${BRIDGE_VERSION}/ha-bridge-${BRIDGE_VERSION}.jar -O /opt/habridge/ha-bridge-${BRIDGE_VERSION}.jar' returned a non-zero code: 1
```

**Comment by jpawlowski** [comment]
I believe you are following instructions of @klein0r.

I may kindly refer you to https://github.com/klein0r/fhem-docker/issues as fhem/fhem-docker is just the basis for Matthias' own Docker image which is hosted there.

**Comment by klein0r** [comment]
I think the image java:8-jdk isn't working on a Raspberry Pi / ARM.

Check the raspbian branch (habridge is based on hypriot/rpi-java:latest):
https://github.com/klein0r/fhem-docker/tree/raspbian
