### ISSUE TITLE
Avoid apt for perl modules in v4 image

### ISSUE THREAD

**Issue by git-developer** [fhem/fhem-docker#210]
_(Migrated from [#115](https://github.com/fhem/fhem-docker/issues/115#issuecomment-2053481654))_

I noticed that the perl library `Nmap::Parser` is installed via apt [in the `Dockerfile`](https://github.com/fhem/fhem-docker/blob/c9c13ccaa4d5288bee8eb406894ef099b5c9998a/Dockerfile-bullseye#L214). According to a [discussion in a different issue](https://github.com/fhem/fhem-docker/issues/115#issuecomment-2053481654), perl packages should no longer be installed via apt in the v4 image.

This issue is a marker to check if this is a bug or not.

**Comment by sidey79** [comment]
#214
