### ISSUE TITLE
For device type SolarForecast the AI library is not included in v4 image

### ISSUE THREAD

**Issue by jmpmn-jr** [fhem/fhem-docker#246]
Hi, 
I use V4 minimal image and added a SolarForecast device (76_SolarForecast.pm, https://fhem.de/commandref.html#76_SolarForecast). The AI functionality check complains that Perl module AI::DecisionTree is missing and proposes to install apt library libai-decisiontree-perl.
I added the library according to the examples to the docker compose script.
I checked that both minimal as well as standard image do not feature this library.

I would like to propose to add the library to the image.  I added the library to the docker compose like this
`
        FROM ghcr.io/fhem/fhem-minimal-docker:4-bullseye
        RUN <<EOF
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get update 
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends  libai-decisiontree-perl
          LC_ALL=C apt-get autoremove -qqy && LC_ALL=C apt-get clean 
        EOF
`

If the library is left out by intention, it would be nice to know the motivation.
Thank you very much  for the effort spent.

**Comment by sidey79** [comment]
I think this is a Bug. I have to check this

**Comment by jmpmn-jr** [comment]
If I can assist pls let me know. It seems my workaround did not work also.
I checked the build outputs, seemed OK. In the container, `apt list | grep libai-decisiontree-perl` shows it. 
But the device inside fhem still complains that the library is not found.
Maybe it's worth to mention that it's not a fresh fhem, already used in the older container.
Cheers

**Comment by sidey79** [comment]
Perl packages which are used by fhem needs to be installed from cpan via CPM or cpanm.

I think i found the bug

**Comment by sidey79** [comment]
I added an fix and this will be implemented in the next release tag.

In the meantime it would be nice if you verify, if AI::Decisiontree works as expexted:

ghcr.io/fhem/fhem-minimal-docker:dev-bullseye

**Comment by jmpmn-jr** [comment]
Hi,
recreated container today with dev tag. Everything seems to work fine. AI support is present. I will use it further to check if there are other effects.
Thanks again!
