### ISSUE TITLE
missing required packages for fhempy

### ISSUE THREAD

**Issue by yalgoo** [fhem/fhem-docker#251]
Hi,
I updated accidentally my fhem/fhem:latest container and the fhempyserver_15733 did not run any longer. After several hours updating, setting up test systems, ... I changed my yaml file to fhem/fhem:bullseye and everything was fine again.
It seems there are missing packages in the lastest docker hub image. Here you can find the required packages for fhempy:
https://github.com/fhempy/fhempy?tab=readme-ov-file

Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 6.1.0-21-amd64
Architecture: x86-64
Hardware Model: ZimaBoard 832
Docker version 27.0.2, build 912c1dd
Dockge image: louislam/dockge:1.4.2

**Comment by sidey79** [comment]
For running fhempy Services there are special Docker Images:

https://github.com/fhem/fhempy-docker
