### ISSUE TITLE
missing GM.pm in image v4

### ISSUE THREAD

**Issue by steffenxx** [fhem/fhem-docker#258]
Since the update to image V4, the ESPEInk module no longer works. The reason seems to be that GM.pm is missing. Here is the error message when FHEM tries to load the module 89_ESPEInk.pm.

`2024.07.14 08:44:47 1: reload: Error:Modul 89_ESPEInk deactivated:
 Can't locate GD.pm in @INC (you may need to install the GD module) (@INC contains: ./FHEM/lib ./lib ./FHEM . /usr/src/app/core/lib/perl5/5.36.3/x86_64-linux-gnu /usr/src/app/core/lib/perl5/5.36.3 /usr/src/app/core/lib/perl5/x86_64-linux-gnu /usr/src/app/core/lib/perl5 /usr/local/lib/perl5/site_perl/5.36.3/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.36.3 /usr/local/lib/perl5/vendor_perl/5.36.3/x86_64-linux-gnu /usr/local/lib/perl5/vendor_perl/5.36.3 /usr/local/lib/perl5/5.36.3/x86_64-linux-gnu /usr/local/lib/perl5/5.36.3) at ./FHEM/89_ESPEInk.pm line 24.
BEGIN failed--compilation aborted at ./FHEM/89_ESPEInk.pm line 24.`

After a downgrade to "fhem/fhem:3-bullseye" the module works fine again.

**Comment by sidey79** [comment]
I have excluded the GD package, but i can`t remeber why :(

Maybe some issues installing it in the image.

**Comment by steffenxx** [comment]
hmm, it was actually always in the image and my ePaper display has been running on it for several years without any problems. It would be nice if it were integrated into the image again.

**Comment by sidey79** [comment]
Im building a new development image, can you test it, when it is finished`?

**Comment by steffenxx** [comment]
Yes of course, I'm happy to test it. Just an aside, I use the fhem-minimal image because I have hombridge and alexa-fhem running in their own container.

**Comment by sidey79** [comment]
This is the test image:

ghcr.io/fhem/fhem-minimal-docker:pr-260-bullseye

**Comment by steffenxx** [comment]
Please excuse the late reply. I was away for a few days. I have just created a container with your image and tried to install ESPEInk. Unfortunately, I still get the same error.

**Comment by sidey79** [comment]
Thank you for testing, this result wasn't expected because the build job ist looking not so bad:

```
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Configuring for libgd version 2.3.0.
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| gdlib.pc not found, guessing the features.
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Included Features:          GD_GIF GD_OPENPOLYGON GD_ZLIB GD_PNG GD_FREETYPE GD_FONTCONFIG GD_JPEG GD_XPM GD_TIFF GD_WEBP GD_UNCLOSEDPOLY GD_FTCIRCLE VERSION_33 WINDOWS_BMP GD2
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| gdlib-config used from the PATH
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Where is libgd installed? [/usr/lib] /usr/lib
#21 190.9 2024-07-18T21:25:32,16,CryptX-0.080| cc -Iltm -Iltc/headers -DLTC_SOURCE -DLTC_NO_TEST -DLTC_NO_PROTOTYPES -DLTM_DESC -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -fPIC -O2  -msse4.1 -maes -DARGTYPE=4 -c ltc/pk/rsa/rsa_decrypt_key.c -o ltc/pk/rsa/rsa_decrypt_key.o
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Warning: prerequisite Test::Fork 0.02 not found.
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Warning: prerequisite Test::NoWarnings 1.00 not found.
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| External LIBS:               -lgd
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Checking if your kit is complete...
#21 190.9 2024-07-18T21:25:32,14,GD-2.83| Looks good
```

**Comment by sidey79** [comment]
I'm building a new image, should be ready in ~ 40 minutes.

This should not fail with the same error.

**Comment by steffenxx** [comment]
Hello Sidey,

Wonderful, now it works perfectly. The device was created without an error message. Converting and uploading to the e-Paper also works. 

Many thanks for the quick help :-) 
When will you go live with the image?

**Comment by sidey79** [comment]
I will make a new release this evening.
