### ISSUE TITLE
CUL_HM version with bugs

### ISSUE THREAD

**Issue by Kollejoe** [fhem/fhem-docker#31]
Hey Folks,

the actual version contains a buggy module --> CUL_HM.pm.
This cause a problem if users try to peer virtual temperature sensors with Homematic thermostats.
To solve this problem users must update the whole system as described here: https://wiki.fhem.de/wiki/Update

@all Contributors: Could you kindly update the whole container to a version with the newest modules? Just to avoid future questions and bug reports. 

Thanks 
Niko

**Comment by sidey79** [comment]
Containers are updated, i think the issue is resolved

@Kollejoe 
can you confirm?
