### ISSUE TITLE
Connection refused from 127.0.0.1:50562

### ISSUE THREAD

**Issue by d1nd141** [fhem/fhem-docker#34]
Hello,

i have lots of messages like:

2021.07.17 13:08:27.623 1: Connection refused from 127.0.0.1:46166
2021.07.17 13:08:49.252 1: Connection refused from 127.0.0.1:46294
2021.07.17 13:09:10.682 1: Connection refused from 127.0.0.1:46452
2021.07.17 13:09:31.986 1: Connection refused from 127.0.0.1:46602
2021.07.17 13:09:53.233 1: Connection refused from 127.0.0.1:46726

I tried to find the cause using tcpdump, but could not find the cause.

I have 2 fhem instances defined.
This one works fine without errors:
docker run --name=fhem-prod --ulimit nofile=98304:98304 -e TELNETPORT=7072 -e CPAN_PKGS="IO::File RPC::XML::Client RPC::XML::Server SubProcess JSON" -d -p 8083:8083 -p 7072:7072 -p 7411:7411 -p 7420:7420 -v /share/CACHEDEV1_DATA/Container/Volumes/fhem:/opt/fhem --restart always fhem/fhem

The second one with the connection attempt errors is defined like:
docker run --name=fhem-test --ulimit nofile=98304:98304 -e TELNETPORT=7072 -e CPAN_PKGS="IO::File RPC::XML::Client RPC::XML::Server SubProcess JSON" -d -p 8084:8083 -p 7074:7072 -p 7511:7511 -p 7520:7520 -p 14211:14211 -v /share/CACHEDEV1_DATA/Container/Volumes/fhem-test:/opt/fhem --restart always fhem/fhem

I also tried to set the telnet port to something other than 7072 -> same issue. (TELNETPORT=xxxx and -p xxxx:xxxx)
The other ports (except web) are for CCU RPC. (rpcserverport set to 5500)

Any idea how to debug this connection attempt?
Thanks

**Comment by sidey79** [comment]
Maybe this is the internal health check which tries to connect to the defined ports.
You have to allow access from localhost to all your telnet and fhemweb definitions.

**Comment by d1nd141** [comment]
That's also what i thought. So i have already set the allowfrom in telnet to
127/8, 10/8, 192.168/16, 172.16/10, 169.254/16
and also tried with 0.0.0.0/0
Error still appears.

**Comment by sidey79** [comment]
try a higher debug level to find out, which definition doesn't allow access

**Comment by d1nd141** [comment]
Excellent idea, i missed that :-)
So i have set the telnet to verbose 0 -> no errors anymore.
verbose 5 echoes the same message as above, but without more info.
So it's clear that it's the telnet port.

I removed the allowfrom and the connection works again.
