### ISSUE TITLE
Jabber is broken for certain servers (e.g. jabber.de)

### ISSUE THREAD

**Issue by git-developer** [fhem/fhem-docker#40]
**Bug description**
- When this Docker image is used for a FHEM instance containing a Jabber client connecting to _jabber.de_, Jabber fails to authenticate and remains _Disconnected_.

**Steps to reproduce**
1. Prepare an account at _jabber.de_
2. Start a container from this Dockerfile.
3. Create a Jabber module instance, e.g.
    ```define jabber Jabber jabber.de 5222 <username> <password> 1 0```
4. Look at the modules internal `CONNINFO`:
    it contains the server response message `error invalid-mechanism`

**Expected behavior**
- The device state should be `Connected`
- The internal `CONNINFO` should contains the message `Connected to jabber.de with username <username>`

**Environment**
- Raspberry Pi 3B+
- Raspbian Buster
- Docker 18.09.1

**Additional context**
- The Dockerfile bundles package `libauthen-sasl-cyrus-perl` which enables support for the SASL authentication mechanism `SCRAM-SHA-1`. This triggers the problem.
- Root cause for the problem is issue https://github.com/dap/XML-Stream/issues/27.
- Summary: when both server and client support more than 1 SASL authentication mechanism, the [XML-Stream](https://github.com/dap/XML-Stream) library that is used within [70_Jabber.pm](https://svn.fhem.de/trac/browser/trunk/fhem/FHEM/70_Jabber.pm) creates an invalid authentication request.

**Workaround**
- The problem does not occur when package `libauthen-sasl-cyrus-perl` is removed from this Dockerfile. This may be done by a tiny `pre-init.sh` script containing the line
    ```shell
    apt-get remove -y libauthen-sasl-cyrus-perl
    ```

**Suggestion**
- Depending on whether `libauthen-sasl-cyrus-perl` is required for other purposes, it may be reasonable to remove this package from the Dockerfile and so avoid the problem without the need for an pre-init script.

**Comment by sidey79** [comment]
I haven't found any hints for what we use this package.

Can you tell us which Image exactly you used?

**Comment by git-developer** [comment]
I'm using current `latest` from Docker Hub on a Raspberry Pi (armv7l):
```sh
$ docker images
REPOSITORY                   TAG                  IMAGE ID            CREATED             SIZE
fhem/fhem                    latest               85af1223416b        11 months ago       1.4GB
```

**Comment by sidey79** [comment]
Can you please confirm, that this Problem also exists with the updated Image which can be found here:

https://github.com/fhem/fhem-docker/pkgs/container/fhem-experimental/9137917?tag=dev

**Comment by git-developer** [comment]
I can confirm that the problem still exists in the newer image, and that removal of `libauthen-sasl-cyrus-perl` fixes it.

***Side note***
The linked development image is not appropriate for use on a current Raspbian host because of https://github.com/moby/moby/issues/40734. Summary:
- Current Raspbian is based on Buster and bundles Docker 18.09.1 and libseccomp 2.3.3-4
- Images based on Bullseye require at least Docker 19.03.9 and libseccomp version 2.4.2

**Comment by sidey79** [comment]
I've created a image based on buster:
https://github.com/fhem/fhem-docker/pkgs/container/fhem-experimental/9603541?tag=dev-buster

Would be nice to get some feedback from you.
