### ISSUE TITLE
Pyhten Link fehlt

### ISSUE THREAD

**Issue by hko123** [fhem/fhem-docker#49]
Für das Fhem-Modul speedtest. wird das Phyton-scipt speedtest benötig.

Dies wirft in fhem den Fehler 

/usr/bin/env: ‘python’: No such file or directory 

In der bash funktioniert es.

Hier wird der link python zu python3 benötigt.

**Comment by sidey79** [comment]
Auf welches Dicker Image bezieht sich dieser Fehler?

**Comment by sidey79** [comment]
Speedtest-cli scheint für python2 ausgelegt zu sein.

Hast Du wie in Troubleshooting vorgeschlagen schon mal die 1. Zeile im Script angepasst?
https://wiki.fhem.de/wiki/Speedtest

**Comment by hko123** [comment]
Ja habe ich gemacht. Hilft auch. Das läuft alles.

Nur ist der Link, nach meiner Einschätzung, die universellere Lösung.

Der Link ist auch in den anderen Images drin.

Danke für den Einsatz und das tolle Image

**Comment by sidey79** [comment]
Ich schau mir das dir Tage an. Hoffentlich bekomme ich heraus durch was dieser Link erzeugt wurde.

**Comment by sidey79** [comment]
Die Änderung ist durch debian bullseye verursacht.

https://packages.debian.org/bullseye/python-is-python2

Ich würde das nicht in das Image integrieren. Du kannst das Paket bei Bedarf über eine Umgebungsvariable beim starten des Containers installieren lassen.
