### ISSUE TITLE
Bullseye image auf docker hub

### ISSUE THREAD

**Issue by DerDoubleD** [fhem/fhem-docker#50]
Könnte man bitte ein image das auf bullseye basiert auf den docker hub legen?

**Comment by sidey79** [comment]
Du kannst aktualisierte Images über Github packages beziehen:

https://github.com/orgs/fhem/packages?repo_name=fhem-docker

Gibt es damit schwierigkeiten?

**Comment by DerDoubleD** [comment]
Ahhh super!
Danke für den Link. Funktioniert ohne Probleme!
Danke!
