### ISSUE TITLE
Crypt::Cipher::AES wird nicht installiert

### ISSUE THREAD

**Issue by hvorragend** [fhem/fhem-docker#8]
Die Pakete Crypt::Cipher::AES werden trotz https://github.com/docker-home-automation-stack/fhem-docker/blob/master/Dockerfile#L173 nicht installiert.

Versuche ich das innerhalb des Containers per Hand, so erscheint folgender Fehler:

```
root@0d63d51780fa:/opt/fhem# sudo cpan Crypt::Cipher::AES
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/root/.cpan/Metadata'
   Database was generated on Tue, 23 Oct 2018 09:29:02 GMT
Running install for module 'Crypt::Cipher::AES'
Checksum for /root/.cpan/sources/authors/id/M/MI/MIK/CryptX-0.061.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIK/CryptX-0.061.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for CryptX
Writing MYMETA.yml and MYMETA.json
   MIK/CryptX-0.061.tar.gz
   /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for M/MI/MIK/CryptX-0.061.tar.gz
   MIK/CryptX-0.061.tar.gz
   make -- NOT OK
```

Scheinbar sind die build-tools erforderlich. Also habe ich manuell 
`apt-get install build-essential`
installiert.

Dies werden im Dockefile zwar vorher installiert und auch nachher wieder per 'purge' entfernt, aber ich kann nicht sagen, warum Crypt::Cipher::AES zwischendurch (auf einer amd64-Architektur) nicht installiert wird.

Beim Erstaufruf von cpan (nicht cpanm) habe ich festgestellt, dass dieses eine Ersteinrichtung durchgeführt hat. Vielleicht ist dies von Interesse.

**Kurz und knapp:**
Kannst du feststellen, wieso Crypt::Cipher::AES auf einer amd64-Plattform nicht installiert wird?

**Comment by jpawlowski** [comment]
fixed by fc9be866e11da0a2027c3e09541dafa5b33e1f5b
