### ISSUE TITLE
LC_MESSAGES=en_DK.UTF-8? Why?

### ISSUE THREAD

**Issue by Kornelius777** [fhem/fhem-docker#86]
...Typo?

Kind regards!

**Comment by sidey79** [comment]
en_DK is a locale which has different time/date format, to fit better to europeans:

https://web.archive.org/web/20200730172228/http://www.ivoras.net/blog/tree/2010-12-20.the-wonderful-en_dk-locale.html

But i can't tell you why this is importand for the image :(

**Comment by Kornelius777** [comment]
I changed it to "de_DE".
Appears to be working fine...
