### ISSUE TITLE
Update nodejs to latest lts 18.x

### ISSUE THREAD

**Issue by volschin** [fhem/fhem-docker#99]
**Is your feature request related to a problem? Please describe.**
Nodejs v14.x reaches its EOL in April 2023. 

**Describe the solution you'd like**
Should be updated to v18.x which is the latest LTS version with EOL in April 2025.
https://github.com/nodejs/release#release-schedule

**Comment by sidey79** [comment]
What is the usage of nodejs inside fhem container, instead of using nodejs in a separate container, can you explain your usecase more detailed?

**Comment by volschin** [comment]
I‘m using the echo module. This is probably to tightly integrated to be run in a separate container. If you see a way to do so, I‘m open to a suggestion.

My alexa-fhem and homebridges are run in a different container.

**Comment by git-developer** [comment]
The latest bullseye image `ghcr.io/fhem/fhem-docker:dev-bullseye` contains nodejs 18, so this issue may probably be closed.
